services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
      # - ./keycloak/data/:/opt/keycloak/data/h2/
    healthcheck:
      test: [ "CMD-SHELL", 'exec 3<>/dev/tcp/127.0.0.1/8080;echo -e "GET /realms/master/.well-known/openid-configuration HTTP/1.1\r\nhost: 127.0.0.1:8080\r\nConnection: close\r\n\r\n" >&3;grep "jwks_uri"  <&3' ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 40s
    ports:
      - "30080:8080"
    command: [ "start-dev", "--metrics-enabled=true", "--health-enabled=true", "--import-realm", "--verbose", "--log-level=INFO", "--features=token-exchange"]
    # entrypoint: [ "bash" ]
    # command: [ "-c", "/opt/keycloak/bin/kc.sh export --realm iceberg --file /opt/keycloak/data/h2/realm-iceberg.json"]
    networks:
      iceberg_net:

  jupyter:
    image: quay.io/jupyter/pyspark-notebook:2024-06-04
    depends_on:
      keycloak:
        condition: service_healthy
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./notebooks:/home/jovyan/authentication
    networks:
      iceberg_net:
    ports:
      - "8888:8888"
      - "34987:34987"  # Callbacks for Authorization Code Flow

networks:
  iceberg_net: